### ISSUE TITLE
SessionContext ITs are flaky

### ISSUE THREAD

**Issue by mcollovati** [vaadin/quarkus#126]
```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.889 s <<< FAILURE! - in com.vaadin.flow.quarkus.it.SessionContextIT
Error:  com.vaadin.flow.quarkus.it.SessionContextIT.httpSessionCloseDestroysSessionContext  Time elapsed: 1.157 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at vaadin.quarkus.production.tests@1.1-SNAPSHOT/com.vaadin.flow.quarkus.it.SessionContextIT.assertDestroyCountEquals(SessionContextIT.java:86)
	at vaadin.quarkus.production.tests@1.1-SNAPSHOT/com.vaadin.flow.quarkus.it.SessionContextIT.httpSessionCloseDestroysSessionContext(SessionContextIT.java:54)
```

**Comment by mcollovati** [comment]
```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.473 s <<< FAILURE! - in com.vaadin.flow.quarkus.it.SessionContextCloseIT
Error:  com.vaadin.flow.quarkus.it.SessionContextCloseIT.vaadinSessionCloseDestroysSessionContext  Time elapsed: 1.459 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at vaadin.quarkus.production.tests@2.0-SNAPSHOT/com.vaadin.flow.quarkus.it.SessionContextCloseIT.assertDestroyCountEquals(SessionContextCloseIT.java:51)
	at vaadin.quarkus.production.tests@2.0-SNAPSHOT/com.vaadin.flow.quarkus.it.SessionContextCloseIT.vaadinSessionCloseDestroysSessionContext(SessionContextCloseIT.java:46)
```

**Comment by mcollovati** [comment]
Reopen because `SessionContextCloseIT` seems still flaky

```
Error:  Failures: 
Error:    SessionContextCloseIT.vaadinSessionCloseDestroysSessionContext:46->assertDestroyCountEquals:51->AbstractCdiIT.waitForCount:45->TestBenchTestCase.waitUntil:201->AbstractCdiIT.lambda$waitForCount$0:47->AbstractCdiIT.assertCountEquals:57 expected:<1> but was:<0>
```

**Comment by mcollovati** [comment]
Another session related flaky test `ServiceIT.sessionDestroyEventObserved`

```
Error:  com.vaadin.flow.quarkus.it.ServiceIT.sessionDestroyEventObserved  Time elapsed: 1.578 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at vaadin.quarkus.development.tests@2.0-SNAPSHOT/com.vaadin.flow.quarkus.it.ServiceIT.sessionDestroyEventObserved(ServiceIT.java:104)
```
