### ISSUE TITLE
Production and native build fail because of missing DevModeStartupListener

### ISSUE THREAD

**Issue by mcollovati** [vaadin/quarkus#158]
When building a native image for a Quarkus application using the Vaadin add-on, an error occurs during native compilation because `DevModeStartupListener` class is missing.

```
Caused by: java.lang.ClassNotFoundException: com.vaadin.base.devserver.startup.DevModeStartupListener
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoader.loadClass(NativeImageClassLoader.java:637)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:529)
        at java.base/java.lang.Class.forName(Class.java:508)
        at com.vaadin.base.devserver.startup.DevModeStartupListener_Bean.<init>(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
```

The class is contained in the `vaadin-dev-server` artifact, that should be excluded for production and native builds.
However, all artifact classes are present in the `vaadin-core-jandex` index, so they are discovered during native build, but not available on classpath.

The `vaadin-dev-server` artifact classes (and probably other dev-mode dependencies) should be removed from the `vaadin-core-jandex` index, and put into a new index (e.g. `vaadin-dev-jandex`) that can be excluded for production and native builds, or it can be a transitive dependency of the `vaadin-dev` artifact, so just excluding that one should be enough.

**Comment by mcollovati** [comment]
The same also happens for production build JAR file, if the `vaadin-dev` dependency is excluded in the `production` profile, as documented in https://vaadin.com/docs/latest/flow/production/production-build#excluding-development-server-module

**Comment by mcollovati** [comment]
A workaround for the JAR production build is to also exclude the vaadin jandex index in the production profile and tell quarkus to re-index vaadin artifacts.

### pom.xml

```xml
<profiles>
    <profile>
        <id>production</id>
        ....
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin</artifactId>
                <exclusions>
                    <exclusion>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-dev</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-quarkus-extension</artifactId>
                <version>${vaadin.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-core-jandex</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
        </dependencies>
    </profile>
</profiles>
```

### application.properties

```
quarkus.index-dependency."all-vaadin".group-id=com.vaadin
```

**Comment by mcollovati** [comment]
List of potentially optional artifacts that might break the build:

* vaadin-dev-server
* flow-react
* flow-polymer-template (only in flow-jandex, artifact is included only in vaadin-spring-bom, so it does not directly affect the quarkus extension)
